preset_base: "minimal"
config_name: "uchain-local"

# Genesis Parameters
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 1
MIN_GENESIS_TIME: 0
GENESIS_FORK_VERSION: "0x00000001"
GENESIS_DELAY: 0

# Time Parameters
SECONDS_PER_SLOT: 12
SLOTS_PER_EPOCH: 32
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 256
SHARD_COMMITTEE_PERIOD: 256
MIN_SEED_LOOKAHEAD: 1
MAX_SEED_LOOKAHEAD: 4
MIN_EPOCHS_TO_INACTIVITY_PENALTY: 4
EPOCHS_PER_ETH1_VOTING_PERIOD: 64
EPOCHS_PER_HISTORICAL_VECTOR: 65536
EPOCHS_PER_SLASHINGS_VECTOR: 8192
HISTORICAL_ROOTS_LIMIT: 16777216
VALIDATOR_REGISTRY_LIMIT: 1099511627776

# Reward and Penalty Parameters
BASE_REWARD_FACTOR: 64
WHISTLEBLOWER_REWARD_QUOTIENT: 512
PROPOSER_REWARD_QUOTIENT: 8
INACTIVITY_PENALTY_QUOTIENT: 33554432
MIN_SLASHING_PENALTY_QUOTIENT: 128
PROPORTIONAL_SLASHING_MULTIPLIER: 1
MAX_PROPOSER_SLASHINGS: 16
MAX_ATTESTER_SLASHINGS: 2
MAX_ATTESTATIONS: 128
MAX_DEPOSITS: 16
MAX_VOLUNTARY_EXITS: 16

# Validator Parameters
EFFECTIVE_BALANCE_INCREMENT: 1000000000
MAX_EFFECTIVE_BALANCE: 32000000000
MIN_DEPOSIT_AMOUNT: 1000000000
EJECTION_BALANCE: 16000000000
ETH1_FOLLOW_DISTANCE: 16
TARGET_COMMITTEE_SIZE: 128
MAX_VALIDATORS_PER_COMMITTEE: 2048
MIN_PER_EPOCH_CHURN_LIMIT: 4
CHURN_LIMIT_QUOTIENT: 65536
SHUFFLE_ROUND_COUNT: 90

# Fork Choice Parameters
SAFE_SLOTS_TO_UPDATE_JUSTIFIED: 8

# State List Lengths
SLOTS_PER_HISTORICAL_ROOT: 8192

# Networking Parameters
SUBNETS_PER_NODE: 2
ATTESTATION_SUBNET_COUNT: 64
ATTESTATION_SUBNET_EXTRA_BITS: 0
ATTESTATION_SUBNET_PREFIX_BITS: 6
MAX_REQUEST_BLOCKS: 1024
EPOCHS_PER_SUBNET_SUBSCRIPTION: 256
MIN_EPOCHS_FOR_BLOCK_REQUESTS: 33024
MAXIMUM_GOSSIP_CLOCK_DISPARITY: 500
ATTESTATION_PROPAGATION_SLOT_RANGE: 32
MESSAGE_DOMAIN_INVALID_SNAPPY: "0x00000000"
MESSAGE_DOMAIN_VALID_SNAPPY: "0x01000000"
MIN_ATTESTATION_INCLUSION_DELAY: 1

# Hysteresis Parameters
HYSTERESIS_QUOTIENT: 4
HYSTERESIS_DOWNWARD_MULTIPLIER: 1
HYSTERESIS_UPWARD_MULTIPLIER: 5

# Execution Layer
SECONDS_PER_ETH1_BLOCK: 14
DEPOSIT_CHAIN_ID: 1337
DEPOSIT_NETWORK_ID: 1337
DEPOSIT_CONTRACT_ADDRESS: "0x9858EfFD232B4033E47d90003D41EC34EcaEda94"

# Beacon Chain initial values
BLS_WITHDRAWAL_PREFIX: "0x00"
ETH1_ADDRESS_WITHDRAWAL_PREFIX: "0x01"

# Additional Committee Parameters
MAX_COMMITTEES_PER_SLOT: 64

# Execution Payload Parameters
MAX_PAYLOAD_SIZE: 1048576

# Deneb Parameters (for modern Teku)
MAX_BLOB_COMMITMENTS_PER_BLOCK: 4096
MAX_BLOBS_PER_BLOCK: 6
