version: "3.7"

# Configuration for UCASH Network Servers (Bootnodes/Validators)
# These nodes accept connections from home users

services:
  besu_el:
    image: hyperledger/besu:latest
    container_name: besu-server-node
    environment:
      - BESU_NETWORK_ID=${NETWORK_ID}
    volumes:
      - ./config:/config
      - besu-data:/opt/besu/data
    ports:
      # Public RPC for users to connect
      - "${BESU_RPC_PORT}:8545"
      - "${BESU_WS_PORT}:8546"
      # P2P port for node discovery
      - "${BESU_P2P_PORT}:30303"
    command:
      - --genesis-file=/config/genesis.json
      - --network-id=${NETWORK_ID}
      - --data-path=/opt/besu/data
      
      # RPC Configuration - Public access
      - --rpc-http-enabled=true
      - --rpc-http-host=0.0.0.0
      - --rpc-http-port=8545
      - --rpc-http-cors-origins=*
      - --rpc-http-api=ETH,NET,WEB3,TXPOOL
      - --host-allowlist=*
      
      # WebSocket for real-time updates
      - --rpc-ws-enabled=true
      - --rpc-ws-host=0.0.0.0
      - --rpc-ws-port=8546
      
      # P2P Networking - ENABLED for network
      - --p2p-enabled=true
      - --p2p-host=0.0.0.0
      - --p2p-port=30303
      - --discovery-enabled=true
      - --max-peers=50
      
      # Server node acts as validator
      - --miner-enabled=true
      - --miner-coinbase=${VALIDATOR_ADDRESS}
      - --node-private-key-file=/config/validator_key
      
      # UCASH Gas Configuration
      - --min-gas-price=2000000000000
      - --target-gas-limit=30000000
      
      # Sync and Storage
      - --sync-mode=FULL
      - --auto-log-bloom-caching-enabled=false
      
    restart: unless-stopped
    networks:
      - ucash-network

networks:
  ucash-network:
    name: ucash-network
    driver: bridge

volumes:
  besu-data:
