version: "3.7"

services:
  # -----------------------------------------------------------------
  # Besu: The Execution Client (EL) 
  # Handles EVM execution, transactions, and state storage.
  # -----------------------------------------------------------------
  besu_el:
    image: hyperledger/besu:latest
    container_name: besu-el-node
    environment:
      # Besu requires these to be set as environment variables for network config
      - BESU_NETWORK_ID=${NETWORK_ID}
    volumes:
      - ./config:/config
      - besu-data:/opt/besu/data
    ports:
      # External ports for dApps/wallets
      - "${BESU_RPC_PORT}:8545"
      - "${BESU_WS_PORT}:8546"
    command:
      - --genesis-file=/config/genesis.json
      - --network-id=${NETWORK_ID}
      - --data-path=/opt/besu/data
      - --rpc-http-enabled=true
      - --rpc-http-host=0.0.0.0
      - --rpc-http-port=8545
      - --rpc-http-cors-origins=*
      - --rpc-http-api=ETH,NET,WEB3,MINER,TXPOOL
      # WebSocket configuration
      - --rpc-ws-enabled=true
      - --rpc-ws-host=0.0.0.0
      - --rpc-ws-port=8546
      # Engine API enabled for PoS consensus
      - --engine-rpc-enabled=true
      - --engine-rpc-port=${ENGINE_API_PORT}
      - --engine-jwt-secret=/config/jwtsecret.hex
      - --engine-host-allowlist=localhost,127.0.0.1,besu_el,teku_cl,teku-cl-node,besu-el-node
      # Host allowlist for Docker networking (include container names and network aliases)
      - --host-allowlist=localhost,127.0.0.1,besu_el,teku_cl,teku-cl-node,besu-el-node
      - --p2p-enabled=false
      - --discovery-enabled=false
      - --sync-mode=FULL
      - --miner-enabled=true
      - --miner-coinbase=0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
      - --node-private-key-file=/config/key
      - --min-gas-price=2000000000000
      - --target-gas-limit=30000000
      - --auto-log-bloom-caching-enabled=false
    restart: unless-stopped
    # Alias the internal network for the consensus client
    networks:
      default:
        aliases:
          - besu_el 

  # -----------------------------------------------------------------
  # Teku: The Consensus Client (CL) and Validator 
  # Handles PoS consensus logic, block proposal, and finality.
  # DISABLED - Using PoA Clique instead for simplicity
  # -----------------------------------------------------------------
  teku_cl_disabled:
    image: consensys/teku:latest 
    container_name: teku-cl-node
    user: "0:0"  # Run as root to avoid permission issues
    volumes:
      - ./config:/config
      - teku-data:/opt/teku/data
    ports:
      # P2P discovery port for the consensus layer
      - "${TEKU_P2P_PORT}:9000"
      # REST API port
      - "5051:5051"
    command:
      # Simplified Teku for development PoS
      - --network=minimal
      - --data-path=/opt/teku/data
      - --ee-endpoint=http://besu_el:8551
      - --ee-jwt-secret-file=/config/jwtsecret.hex
      - --eth1-endpoint=http://besu_el:8545
      - --validators-proposer-default-fee-recipient=0x9858EfFD232B4033E47d90003D41EC34EcaEda94
      - --p2p-enabled=false
      - --rest-api-enabled=true
      - --rest-api-interface=0.0.0.0
      - --rest-api-port=5051
      - --log-destination=CONSOLE
      - --logging=INFO
      - --Xstartup-target-peer-count=0
    restart: unless-stopped
    depends_on:
      - besu_el
    # Alias the internal network for Besu to find it
    networks:
      default:
        aliases:
          - teku_cl

volumes:
  besu-data:
  teku-data:
